version: '3'
services:
  db:
    image: mysql:5.7.11
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    image: php-mysql
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    links:
      - db
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 2222:80
    environment:
      MYSQL_ROOT_PASSWORD: root
  sass:
    image: larryprice/sass
    volumes:
      - ./app/css:/src